POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Something entirely different",
  "author": "Broken Stephie",
  "url": "https://fullstackopen.com/en/part4/user_administration#creating-a-new-note",
  "likes": 15
}